#!/usr/bin/env bash
#
# Deploy sws-runtime + SPA + systemd assets to a single Pixsys Yocto device.
#
# Prereqs:
#   - Build done: ./scripts/yocto/build.sh (release default)
#   - You can already ssh + sudo to the device:
#       ssh-copy-id -i ~/.ssh/id_ed25519.pub pixsys@<host>
#     (the maintainer does this by hand; see docs/TEST_SETUPS.md)
#
# Usage:
#   ./scripts/yocto/deploy.sh <user@host>           # release binary + restart
#   ./scripts/yocto/deploy.sh <user@host> --no-restart
#   ./scripts/yocto/deploy.sh <user@host> --debug   # deploy debug binary
#
# Layout on device (created on first install):
#   /data/user/sws/
#     sws-runtime              (binary)
#     sws-runtime-launch.sh    (env + exec wrapper)
#     runtime.env              (per-device overrides — never overwritten)
#     config/                  (TLS certs, generated by runtime on first start)
#     projects/                (operator projects)
#     templates/               (bundled templates from this repo)
#     www/                     (SPA dist served at /)
#     historian.db             (created by runtime on first start)
#
# systemd unit at /etc/systemd/system/sws-runtime.service.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

if [ $# -lt 1 ]; then
  echo "usage: $0 <user@host> [--debug] [--no-restart]" >&2
  exit 2
fi

TARGET_HOST="$1"
shift

PROFILE="release"
DO_RESTART=1
for arg in "$@"; do
  case "$arg" in
    --debug)       PROFILE="debug" ;;
    --release)     PROFILE="release" ;;
    --no-restart)  DO_RESTART=0 ;;
    *) echo "[deploy] unknown arg: $arg" >&2; exit 2 ;;
  esac
done

BIN="$REPO_ROOT/sws-runtime/target/aarch64-unknown-linux-gnu/$PROFILE/sws-runtime"
SPA_DIST="$REPO_ROOT/sws-editor/dist"
TEMPLATES="$REPO_ROOT/examples/templates"
UNIT="$REPO_ROOT/deploy/yocto/sws-runtime.service"
LAUNCH="$REPO_ROOT/deploy/yocto/sws-runtime-launch.sh"

# ── Sanity ───────────────────────────────────────────────────────────────────

for f in "$BIN" "$UNIT" "$LAUNCH"; do
  if [ ! -f "$f" ]; then
    echo "[deploy] ERROR: missing artefact: $f" >&2
    [ "$f" = "$BIN" ] && echo "  → run ./scripts/yocto/build.sh first" >&2
    exit 1
  fi
done

if [ ! -d "$SPA_DIST" ]; then
  echo "[deploy] WARNING: SPA dist not found at $SPA_DIST — UI won't be served." >&2
  echo "  → run ./scripts/yocto/build.sh (with default --www) or 'cd sws-editor && pnpm build'" >&2
fi

# ── Stage payload on device under /tmp, then sudo-move into place ────────────
#
# rsync is faster on re-deploy (delta). Fall back to scp if rsync isn't on
# the device. Both go via the same SSH connection multiplexing window
# defined in ~/.ssh/config — nothing fancy.

# Staging dir lives under the device's writable partition. Pixsys Yocto boxes
# typically have / as a read-only squashfs/ubifs; /data/user is the operator
# scratch area. The post-staging `sudo install` step moves files into
# /data/user/sws (which is on the same partition — instant rename, no copy).
STAGE="/data/user/sws-deploy-$$"

# shellcheck disable=SC2029
ssh "$TARGET_HOST" "mkdir -p $STAGE/www $STAGE/templates"

echo "[deploy] pushing binary…"
scp -q "$BIN" "$TARGET_HOST:$STAGE/sws-runtime"

echo "[deploy] pushing launch wrapper + systemd unit…"
scp -q "$LAUNCH" "$TARGET_HOST:$STAGE/sws-runtime-launch.sh"
scp -q "$UNIT"   "$TARGET_HOST:$STAGE/sws-runtime.service"

if [ -d "$SPA_DIST" ]; then
  echo "[deploy] pushing SPA bundle…"
  if command -v rsync >/dev/null 2>&1 \
     && ssh "$TARGET_HOST" 'command -v rsync >/dev/null'; then
    rsync -az --delete "$SPA_DIST/" "$TARGET_HOST:$STAGE/www/"
  else
    scp -q -r "$SPA_DIST/." "$TARGET_HOST:$STAGE/www/"
  fi
fi

if [ -d "$TEMPLATES" ]; then
  echo "[deploy] pushing project templates…"
  if command -v rsync >/dev/null 2>&1 \
     && ssh "$TARGET_HOST" 'command -v rsync >/dev/null'; then
    rsync -az --delete "$TEMPLATES/" "$TARGET_HOST:$STAGE/templates/"
  else
    scp -q -r "$TEMPLATES/." "$TARGET_HOST:$STAGE/templates/"
  fi
fi

# ── Install on device ────────────────────────────────────────────────────────

RESTART_BLOCK=""
if [ "$DO_RESTART" -eq 1 ]; then
  RESTART_BLOCK='sudo systemctl daemon-reload && sudo systemctl enable --now sws-runtime.service && sudo systemctl restart sws-runtime.service && sleep 1 && sudo systemctl --no-pager status sws-runtime.service | head -20'
fi

# shellcheck disable=SC2087
ssh -t "$TARGET_HOST" bash <<EOF
set -euo pipefail

STAGE="$STAGE"
sudo mkdir -p /data/user/sws/config /data/user/sws/projects /data/user/sws/templates /data/user/sws/www

sudo install -m 0755 "\$STAGE/sws-runtime"            /data/user/sws/sws-runtime
sudo install -m 0755 "\$STAGE/sws-runtime-launch.sh"  /data/user/sws/sws-runtime-launch.sh

# runtime.env is seeded once and never overwritten — operator-editable.
if [ ! -f /data/user/sws/runtime.env ]; then
  sudo tee /data/user/sws/runtime.env >/dev/null <<'ENV'
# Per-device overrides for sws-runtime. Edit and: sudo systemctl restart sws-runtime
# (default credentials below are for the FIRST LOGIN ONLY — change them!)
SWS_ADMIN_USER=admin
SWS_ADMIN_PASSWORD=admin
ENV
  sudo chmod 0600 /data/user/sws/runtime.env
fi

if [ -d "\$STAGE/www" ]; then
  sudo rm -rf /data/user/sws/www
  sudo mv     "\$STAGE/www" /data/user/sws/www
fi

if [ -d "\$STAGE/templates" ]; then
  sudo rm -rf /data/user/sws/templates
  sudo mv     "\$STAGE/templates" /data/user/sws/templates
fi

sudo install -m 0644 "\$STAGE/sws-runtime.service" /etc/systemd/system/sws-runtime.service

rm -rf "\$STAGE"

$RESTART_BLOCK
EOF

echo
echo "[deploy] done. Quick check from this host:"
case "$TARGET_HOST" in
  *@*) HOST_PART="${TARGET_HOST#*@}" ;;
  *)   HOST_PART="$TARGET_HOST" ;;
esac
echo "  curl -k https://$HOST_PART:8443/health"
