[package]
name    = "sws-plugin-enip"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio.workspace      = true
serde.workspace      = true
tracing.workspace    = true
anyhow.workspace     = true
tokio-util.workspace = true
rseip.workspace      = true
sws-core = { path = "../sws-core" }
