[package]
name    = "sws-audit"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio.workspace   = true
serde.workspace   = true
serde_json.workspace = true
tracing.workspace = true
anyhow.workspace  = true
sha2.workspace    = true
hmac              = "0.12"
