[package]
name    = "sws-plugin-mqtt"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio.workspace     = true
rumqttc.workspace   = true
rumqttd.workspace   = true
serde.workspace     = true
tracing.workspace   = true
anyhow.workspace    = true
sws-plugin-api = { path = "../sws-plugin-api" }
