[package]
name    = "sws-kiosk"
version = "0.1.0-dev"
edition = "2021"

[[bin]]
name = "sws-kiosk"
path = "src/main.rs"

[dependencies]
gtk4    = { version = "0.11", features = ["v4_10"] }
webkit6 = { version = "0.6", features = ["v2_42"] }
glib    = "0.20"
clap    = { version = "4", features = ["derive"] }
