[package]
name    = "sws-plugin-modbus"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio.workspace        = true
tokio-modbus.workspace = true
serde.workspace        = true
tracing.workspace      = true
anyhow.workspace       = true
sws-core       = { path = "../sws-core" }
sws-plugin-api = { path = "../sws-plugin-api" }
