// @generated da scripts/gen_synoptic_schema.py — NON modificare a mano.
// Rigenera con `./scripts/gen_synoptic_schema.py`; la guardia
// `scripts/check_synoptic_schema.sh` fallisce se questo file è vecchio.
//
// Serve all'assistente IA dell'editor: senza un vocabolario chiuso il
// modello inventa nomi di campo plausibili, serde li scarta in silenzio,
// e il difetto si vede solo sul pannello.

/// Un campo di una struttura del progetto, con la sua documentazione.
#[derive(Debug, Clone, Copy, serde::Serialize)]
pub struct Field {
    pub name: &'static str,
    /// Tipo ridotto: string | number | bool | any | object | <tipo>[] | <struct>
    pub ty: &'static str,
    pub required: bool,
    /// Intestazione di sezione sotto cui il campo è dichiarato (può essere vuota).
    pub group: &'static str,
    /// Il commento di documentazione del campo, così com'è nel sorgente.
    pub doc: &'static str,
}

/// I campi di un oggetto sinottico (da sws-web/src/synoptic.rs).
pub const OBJECT_FIELDS: &[Field] = &[
    Field { name: "id", ty: "string", required: true, group: "", doc: "" },
    Field { name: "name", ty: "string", required: false, group: "", doc: "" },
    Field { name: "type", ty: "string", required: true, group: "", doc: "" },
    Field { name: "x", ty: "number", required: true, group: "", doc: "" },
    Field { name: "y", ty: "number", required: true, group: "", doc: "" },
    Field { name: "width", ty: "number", required: false, group: "Geometry", doc: "" },
    Field { name: "height", ty: "number", required: false, group: "Geometry", doc: "" },
    Field { name: "fill", ty: "string", required: false, group: "Appearance", doc: "" },
    Field { name: "bg_color", ty: "string", required: false, group: "object's own content — same convention grid cells already used.", doc: "" },
    Field { name: "bg_image", ty: "string", required: false, group: "object's own content — same convention grid cells already used.", doc: "" },
    Field { name: "axis_color", ty: "string", required: false, group: "Chart axes/grid colors (trend today, shared by future chart widgets).", doc: "" },
    Field { name: "grid_color", ty: "string", required: false, group: "Chart axes/grid colors (trend today, shared by future chart widgets).", doc: "" },
    Field { name: "stroke", ty: "string", required: false, group: "Chart axes/grid colors (trend today, shared by future chart widgets).", doc: "" },
    Field { name: "stroke_width", ty: "number", required: false, group: "Chart axes/grid colors (trend today, shared by future chart widgets).", doc: "" },
    Field { name: "x2", ty: "number", required: false, group: "Line endpoint", doc: "" },
    Field { name: "y2", ty: "number", required: false, group: "Line endpoint", doc: "" },
    Field { name: "tag", ty: "string", required: false, group: "Tag binding", doc: "" },
    Field { name: "format", ty: "string", required: false, group: "Tag binding", doc: "" },
    Field { name: "label", ty: "string", required: false, group: "Text / label", doc: "" },
    Field { name: "src", ty: "string", required: false, group: "Text / label", doc: "" },
    Field { name: "write_value", ty: "any", required: false, group: "Control write", doc: "" },
    Field { name: "button_mode", ty: "string", required: false, group: "F3 — pipeline di comando", doc: "" },
    Field { name: "release_value", ty: "any", required: false, group: "F3 — pipeline di comando", doc: "" },
    Field { name: "require_confirm", ty: "bool", required: false, group: "F3 — pipeline di comando", doc: "" },
    Field { name: "confirm_message", ty: "string", required: false, group: "F3 — pipeline di comando", doc: "" },
    Field { name: "min_role", ty: "string", required: false, group: "F3 — pipeline di comando", doc: "" },
    Field { name: "min_role_effect", ty: "string", required: false, group: "F3 — pipeline di comando", doc: "" },
    Field { name: "blink_mode", ty: "string", required: false, group: "F4 — allarmi e qualità per-oggetto", doc: "" },
    Field { name: "blink_tag", ty: "string", required: false, group: "F4 — allarmi e qualità per-oggetto", doc: "" },
    Field { name: "blink_rate_ms", ty: "number", required: false, group: "F4 — allarmi e qualità per-oggetto", doc: "" },
    Field { name: "show_alarm_state", ty: "bool", required: false, group: "F4 — allarmi e qualità per-oggetto", doc: "" },
    Field { name: "bad_value_style", ty: "string", required: false, group: "F4 — allarmi e qualità per-oggetto", doc: "" },
    Field { name: "stale_after_s", ty: "number", required: false, group: "F4 — allarmi e qualità per-oggetto", doc: "" },
    Field { name: "critical", ty: "bool", required: false, group: "F4 — allarmi e qualità per-oggetto", doc: "" },
    Field { name: "require_reason", ty: "bool", required: false, group: "F4 — allarmi e qualità per-oggetto", doc: "" },
    Field { name: "write_on_release", ty: "bool", required: false, group: "F4 — allarmi e qualità per-oggetto", doc: "" },
    Field { name: "write_deadband", ty: "number", required: false, group: "F4 — allarmi e qualità per-oggetto", doc: "" },
    Field { name: "checked_value", ty: "any", required: false, group: "F4 — allarmi e qualità per-oggetto", doc: "" },
    Field { name: "unchecked_value", ty: "any", required: false, group: "F4 — allarmi e qualità per-oggetto", doc: "" },
    Field { name: "target_page", ty: "string", required: false, group: "Navigation", doc: "" },
    Field { name: "min", ty: "number", required: false, group: "Numeric range", doc: "" },
    Field { name: "max", ty: "number", required: false, group: "Numeric range", doc: "" },
    Field { name: "unit", ty: "string", required: false, group: "Numeric range", doc: "" },
    Field { name: "decimals", ty: "number", required: false, group: "Numeric range", doc: "" },
    Field { name: "step", ty: "number", required: false, group: "Numeric range", doc: "" },
    Field { name: "warn_low", ty: "number", required: false, group: "Thresholds", doc: "" },
    Field { name: "warn_high", ty: "number", required: false, group: "Thresholds", doc: "" },
    Field { name: "alarm_low", ty: "number", required: false, group: "Thresholds", doc: "" },
    Field { name: "alarm_high", ty: "number", required: false, group: "Thresholds", doc: "" },
    Field { name: "on_value", ty: "any", required: false, group: "LED", doc: "" },
    Field { name: "on_color", ty: "string", required: false, group: "LED", doc: "" },
    Field { name: "off_color", ty: "string", required: false, group: "LED", doc: "" },
    Field { name: "show_value", ty: "bool", required: false, group: "Flags", doc: "" },
    Field { name: "read_only", ty: "bool", required: false, group: "Flags", doc: "" },
    Field { name: "orientation", ty: "string", required: false, group: "Flags", doc: "" },
    Field { name: "options", ty: "any", required: false, group: "Radio options / table rows (generic JSON arrays)", doc: "" },
    Field { name: "table_rows", ty: "any", required: false, group: "Radio options / table rows (generic JSON arrays)", doc: "" },
    Field { name: "window_s", ty: "number", required: false, group: "Trend chart", doc: "" },
    Field { name: "y_min", ty: "number", required: false, group: "Trend chart", doc: "" },
    Field { name: "y_max", ty: "number", required: false, group: "Trend chart", doc: "" },
    Field { name: "line_color", ty: "string", required: false, group: "Trend chart", doc: "" },
    Field { name: "extra_tags", ty: "string[]", required: false, group: "Trend chart", doc: "" },
    Field { name: "opcua_backfill", ty: "bool", required: false, group: "Trend chart", doc: "When true, backfills from the OPC-UA server's historian on mount. Was missing from this mirror (same round-trip-drop gap as `auto_rotate_skip` above) — the checkbox in the editor appeared to work until the next save/reload silently reset it." },
    Field { name: "trend_series_styles", ty: "any", required: false, group: "Trend chart", doc: "Per-trace style overrides (width/dash/fill/smooth/color), parallel to [tag, ...extra_tags]. Generic JSON passthrough like `options`/`table_rows` above — the frontend owns the shape (see TrendSeriesStyle in types/index.ts)." },
    Field { name: "pan_step_s", ty: "number", required: false, group: "Trend chart", doc: "Seconds moved per ◀/▶ pan click on the compact Trend widget. Defaults to 25% of window_s when unset." },
    Field { name: "trend_dt_date_order", ty: "string", required: false, group: "Trend date/time format (axis labels + hover tooltip)", doc: "" },
    Field { name: "trend_dt_separator", ty: "string", required: false, group: "Trend date/time format (axis labels + hover tooltip)", doc: "" },
    Field { name: "trend_dt_time_format", ty: "string", required: false, group: "Trend date/time format (axis labels + hover tooltip)", doc: "" },
    Field { name: "trend_dt_show_seconds", ty: "bool", required: false, group: "Trend date/time format (axis labels + hover tooltip)", doc: "" },
    Field { name: "trend_dt_show_year", ty: "bool", required: false, group: "Trend date/time format (axis labels + hover tooltip)", doc: "" },
    Field { name: "trend_dt_two_lines", ty: "bool", required: false, group: "Trend date/time format (axis labels + hover tooltip)", doc: "" },
    Field { name: "trend_dt_always_show_date", ty: "bool", required: false, group: "Trend date/time format (axis labels + hover tooltip)", doc: "" },
    Field { name: "trend_show_thresholds", ty: "bool", required: false, group: "Trend date/time format (axis labels + hover tooltip)", doc: "" },
    Field { name: "trend_show_alarm_markers", ty: "bool", required: false, group: "Trend date/time format (axis labels + hover tooltip)", doc: "" },
    Field { name: "trend_log_scale", ty: "bool", required: false, group: "Trend date/time format (axis labels + hover tooltip)", doc: "" },
    Field { name: "trend_tags", ty: "any", required: false, group: "Trend date/time format (axis labels + hover tooltip)", doc: "Tracce unificate del trend (migrazione 2026-08-23): [{tag,label,color,…}]. I campi legacy tag/extra_tags/trend_series_styles/line_color restano per i progetti non ancora ri-salvati." },
    Field { name: "datalog_page_size", ty: "number", required: false, group: "Trend date/time format (axis labels + hover tooltip)", doc: "" },
    Field { name: "symbol_states", ty: "any", required: false, group: "F6.6/F6.10 — simboli N-stati, rotazione, flusso pipe", doc: "" },
    Field { name: "symbol_spin", ty: "string", required: false, group: "F6.6/F6.10 — simboli N-stati, rotazione, flusso pipe", doc: "" },
    Field { name: "symbol_spin_tag", ty: "string", required: false, group: "F6.6/F6.10 — simboli N-stati, rotazione, flusso pipe", doc: "" },
    Field { name: "symbol_spin_s", ty: "number", required: false, group: "F6.6/F6.10 — simboli N-stati, rotazione, flusso pipe", doc: "" },
    Field { name: "pipe_flow", ty: "bool", required: false, group: "F6.6/F6.10 — simboli N-stati, rotazione, flusso pipe", doc: "" },
    Field { name: "pipe_flow_tag", ty: "string", required: false, group: "F6.6/F6.10 — simboli N-stati, rotazione, flusso pipe", doc: "" },
    Field { name: "motion_path", ty: "any", required: false, group: "F6.6/F6.10 — simboli N-stati, rotazione, flusso pipe", doc: "" },
    Field { name: "motion_tag", ty: "string", required: false, group: "F6.6/F6.10 — simboli N-stati, rotazione, flusso pipe", doc: "" },
    Field { name: "motion_min", ty: "number", required: false, group: "F6.6/F6.10 — simboli N-stati, rotazione, flusso pipe", doc: "" },
    Field { name: "motion_max", ty: "number", required: false, group: "F6.6/F6.10 — simboli N-stati, rotazione, flusso pipe", doc: "" },
    Field { name: "motion_anchor", ty: "string", required: false, group: "F6.6/F6.10 — simboli N-stati, rotazione, flusso pipe", doc: "" },
    Field { name: "corner_radius", ty: "number", required: false, group: "F7.6 — rifiniture di forma (rect/ellipse, gauge, led, grid, image)", doc: "" },
    Field { name: "fill_gradient", ty: "string", required: false, group: "F7.6 — rifiniture di forma (rect/ellipse, gauge, led, grid, image)", doc: "" },
    Field { name: "gauge_zones", ty: "any", required: false, group: "F7.6 — rifiniture di forma (rect/ellipse, gauge, led, grid, image)", doc: "" },
    Field { name: "gauge_ticks", ty: "number", required: false, group: "F7.6 — rifiniture di forma (rect/ellipse, gauge, led, grid, image)", doc: "" },
    Field { name: "gauge_start_angle", ty: "number", required: false, group: "F7.6 — rifiniture di forma (rect/ellipse, gauge, led, grid, image)", doc: "" },
    Field { name: "gauge_end_angle", ty: "number", required: false, group: "F7.6 — rifiniture di forma (rect/ellipse, gauge, led, grid, image)", doc: "" },
    Field { name: "gauge_sp_tag", ty: "string", required: false, group: "F7.6 — rifiniture di forma (rect/ellipse, gauge, led, grid, image)", doc: "" },
    Field { name: "gauge_sp_color", ty: "string", required: false, group: "F7.6 — rifiniture di forma (rect/ellipse, gauge, led, grid, image)", doc: "" },
    Field { name: "led_shape", ty: "string", required: false, group: "F7.6 — rifiniture di forma (rect/ellipse, gauge, led, grid, image)", doc: "" },
    Field { name: "grid_gap", ty: "number", required: false, group: "F7.6 — rifiniture di forma (rect/ellipse, gauge, led, grid, image)", doc: "" },
    Field { name: "grid_padding", ty: "number", required: false, group: "F7.6 — rifiniture di forma (rect/ellipse, gauge, led, grid, image)", doc: "" },
    Field { name: "image_fit", ty: "string", required: false, group: "F7.6 — rifiniture di forma (rect/ellipse, gauge, led, grid, image)", doc: "" },
    Field { name: "text_wrap", ty: "bool", required: false, group: "F7.4 — testo multiriga", doc: "" },
    Field { name: "text_valign", ty: "string", required: false, group: "F7.4 — testo multiriga", doc: "" },
    Field { name: "line_height", ty: "number", required: false, group: "F7.4 — testo multiriga", doc: "" },
    Field { name: "bar_mode", ty: "string", required: false, group: "F7.2 — bar chart", doc: "" },
    Field { name: "bar_ticks", ty: "number", required: false, group: "F7.2 — bar chart", doc: "" },
    Field { name: "bar_show_legend", ty: "bool", required: false, group: "F7.2 — bar chart", doc: "" },
    Field { name: "pie_label_mode", ty: "string", required: false, group: "F7.3 — pie chart", doc: "" },
    Field { name: "pie_group_below_pct", ty: "number", required: false, group: "F7.3 — pie chart", doc: "" },
    Field { name: "pie_group_label", ty: "string", required: false, group: "F7.3 — pie chart", doc: "" },
    Field { name: "pie_group_color", ty: "string", required: false, group: "F7.3 — pie chart", doc: "" },
    Field { name: "pie_explode_px", ty: "number", required: false, group: "F7.3 — pie chart", doc: "" },
    Field { name: "pie_hole_color", ty: "string", required: false, group: "F7.3 — pie chart", doc: "" },
    Field { name: "table_columns", ty: "any", required: false, group: "F7.1 — table 2.0 (le opzioni per-riga viaggiano dentro table_rows, Value)", doc: "" },
    Field { name: "table_sortable", ty: "bool", required: false, group: "F7.1 — table 2.0 (le opzioni per-riga viaggiano dentro table_rows, Value)", doc: "" },
    Field { name: "table_filterable", ty: "bool", required: false, group: "F7.1 — table 2.0 (le opzioni per-riga viaggiano dentro table_rows, Value)", doc: "" },
    Field { name: "table_font_size", ty: "number", required: false, group: "F7.1 — table 2.0 (le opzioni per-riga viaggiano dentro table_rows, Value)", doc: "" },
    Field { name: "table_label_header", ty: "string", required: false, group: "F7.1 — table 2.0 (le opzioni per-riga viaggiano dentro table_rows, Value)", doc: "" },
    Field { name: "alarm_viewer_show_ack_all", ty: "bool", required: false, group: "F7.5 — allarmi: ACK massivo, messa in silenzio, storico piazzabile", doc: "" },
    Field { name: "alarm_viewer_show_shelve", ty: "bool", required: false, group: "F7.5 — allarmi: ACK massivo, messa in silenzio, storico piazzabile", doc: "" },
    Field { name: "alarm_shelve_minutes", ty: "number", required: false, group: "F7.5 — allarmi: ACK massivo, messa in silenzio, storico piazzabile", doc: "" },
    Field { name: "alarm_history_id", ty: "string", required: false, group: "F7.5 — allarmi: ACK massivo, messa in silenzio, storico piazzabile", doc: "" },
    Field { name: "alarm_bell_sound", ty: "bool", required: false, group: "F7.5 — allarmi: ACK massivo, messa in silenzio, storico piazzabile", doc: "" },
    Field { name: "alarm_bell_sound_severities", ty: "any", required: false, group: "F7.5 — allarmi: ACK massivo, messa in silenzio, storico piazzabile", doc: "" },
    Field { name: "alarm_bell_sound_repeat_s", ty: "number", required: false, group: "F7.5 — allarmi: ACK massivo, messa in silenzio, storico piazzabile", doc: "" },
    Field { name: "y_tag", ty: "string", required: false, group: "XY plot (live point + trail, not a time series). `tag` above is the X axis.", doc: "" },
    Field { name: "xy_trail_s", ty: "number", required: false, group: "XY plot (live point + trail, not a time series). `tag` above is the X axis.", doc: "" },
    Field { name: "xy_x_min", ty: "number", required: false, group: "XY plot (live point + trail, not a time series). `tag` above is the X axis.", doc: "" },
    Field { name: "xy_x_max", ty: "number", required: false, group: "XY plot (live point + trail, not a time series). `tag` above is the X axis.", doc: "" },
    Field { name: "xy_y_min", ty: "number", required: false, group: "XY plot (live point + trail, not a time series). `tag` above is the X axis.", doc: "" },
    Field { name: "xy_y_max", ty: "number", required: false, group: "XY plot (live point + trail, not a time series). `tag` above is the X axis.", doc: "" },
    Field { name: "z_index", ty: "number", required: false, group: "Layer / visibility (cross-cutting)", doc: "" },
    Field { name: "visible", ty: "bool", required: false, group: "Layer / visibility (cross-cutting)", doc: "" },
    Field { name: "visible_tag", ty: "string", required: false, group: "Layer / visibility (cross-cutting)", doc: "" },
    Field { name: "on_press_fn", ty: "string", required: false, group: "(The legacy raw-code form is intentionally not honoured anymore.)", doc: "" },
    Field { name: "on_release_fn", ty: "string", required: false, group: "(The legacy raw-code form is intentionally not honoured anymore.)", doc: "" },
    Field { name: "on_press_args", ty: "any", required: false, group: "(The legacy raw-code form is intentionally not honoured anymore.)", doc: "Per-binding overrides for the picked function's parameters." },
    Field { name: "on_release_args", ty: "any", required: false, group: "(The legacy raw-code form is intentionally not honoured anymore.)", doc: "" },
    Field { name: "text", ty: "string", required: false, group: "Text object styling", doc: "" },
    Field { name: "font_size", ty: "number", required: false, group: "Text object styling", doc: "" },
    Field { name: "font_family", ty: "string", required: false, group: "Text object styling", doc: "" },
    Field { name: "font_weight", ty: "Option<Value>, // string (\"bold\") or number (700)", required: false, group: "Text object styling", doc: "" },
    Field { name: "font_style", ty: "string", required: false, group: "Text object styling", doc: "" },
    Field { name: "text_anchor", ty: "string", required: false, group: "Text object styling", doc: "" },
    Field { name: "color", ty: "string", required: false, group: "Text object styling", doc: "" },
    Field { name: "text_color_by_threshold", ty: "bool", required: false, group: "Text object styling", doc: "" },
    Field { name: "symbol_id", ty: "string", required: false, group: "Built-in SCADA symbol (type === \"symbol\")", doc: "Quale simbolo disegnare: uno degli id della libreria (l'elenco completo è in `FIELD_ENUMS`), oppure `custom:<id>` per un simbolo caricato nel progetto. Attenzione: tredici della serie valvole e processo (`valve_3way`, `check_valve`, `silo`, `conveyor`, `furnace`…) esistono solo nel browser — sul pannello LVGL rendono un riquadro d'errore, vedi Q15." },
    Field { name: "state_off_color", ty: "string", required: false, group: "Built-in SCADA symbol (type === \"symbol\")", doc: "" },
    Field { name: "state_on_color", ty: "string", required: false, group: "Built-in SCADA symbol (type === \"symbol\")", doc: "" },
    Field { name: "state_alarm_color", ty: "string", required: false, group: "Built-in SCADA symbol (type === \"symbol\")", doc: "" },
    Field { name: "state_tag", ty: "string", required: false, group: "Built-in SCADA symbol (type === \"symbol\")", doc: "" },
    Field { name: "alarm_tag", ty: "string", required: false, group: "Built-in SCADA symbol (type === \"symbol\")", doc: "" },
    Field { name: "rotation", ty: "number", required: false, group: "Built-in SCADA symbol (type === \"symbol\")", doc: "Rotation in degrees around the bounding-box centre." },
    Field { name: "flip_h", ty: "bool", required: false, group: "Built-in SCADA symbol (type === \"symbol\")", doc: "Mirror along the vertical axis." },
    Field { name: "flip_v", ty: "bool", required: false, group: "Built-in SCADA symbol (type === \"symbol\")", doc: "Mirror along the horizontal axis." },
    Field { name: "opacity", ty: "number", required: false, group: "Built-in SCADA symbol (type === \"symbol\")", doc: "Opacity 0..1 (default 1)." },
    Field { name: "transition_duration_ms", ty: "number", required: false, group: "Built-in SCADA symbol (type === \"symbol\")", doc: "Optional CSS transition duration (ms) for CSS-animatable bound props (fill / stroke / opacity / transform). 0 or absent → no animation." },
    Field { name: "bindings", ty: "object", required: false, group: "Built-in SCADA symbol (type === \"symbol\")", doc: "Generic prop-to-tag bindings. Keys are SynopticObject prop names. F2: il valore può essere una stringa (tag id, forma storica) oppure un oggetto BindingSpec {tag, in_min…out_max, clamp} / {expr}. Passthrough opaco: il runtime non lo interpreta, lo conserva e lo serve alla SPA." },
    Field { name: "grid_rows", ty: "number", required: false, group: "Grid layout object (type === \"grid\")", doc: "" },
    Field { name: "grid_cols", ty: "number", required: false, group: "Grid layout object (type === \"grid\")", doc: "" },
    Field { name: "col_widths", ty: "any", required: false, group: "Grid layout object (type === \"grid\")", doc: "" },
    Field { name: "row_heights", ty: "any", required: false, group: "Grid layout object (type === \"grid\")", doc: "" },
    Field { name: "grid_cells", ty: "any", required: false, group: "spans via rowspan/colspan) ride along without schema changes here.", doc: "" },
    Field { name: "grid_show_borders", ty: "bool", required: false, group: "spans via rowspan/colspan) ride along without schema changes here.", doc: "" },
    Field { name: "grid_border_color", ty: "string", required: false, group: "spans via rowspan/colspan) ride along without schema changes here.", doc: "" },
    Field { name: "quality_dot", ty: "bool", required: false, group: "Quality dot", doc: "" },
    Field { name: "quality_dot_good_color", ty: "string", required: false, group: "Quality dot", doc: "" },
    Field { name: "quality_dot_bad_color", ty: "string", required: false, group: "Quality dot", doc: "" },
    Field { name: "quality_dot_uncertain_color", ty: "string", required: false, group: "Quality dot", doc: "" },
    Field { name: "locked", ty: "bool", required: false, group: "Editor-only metadata", doc: "" },
    Field { name: "group_id", ty: "string", required: false, group: "Editor-only metadata", doc: "" },
    Field { name: "button_action", ty: "any", required: false, group: "the raw `type` field directly; the backend never interprets it.", doc: "" },
    Field { name: "alarm_viewer_max_rows", ty: "number", required: false, group: "same class of bug documented above for auto_rotate_skip/opcua_backfill.", doc: "" },
    Field { name: "alarm_viewer_severities", ty: "any", required: false, group: "same class of bug documented above for auto_rotate_skip/opcua_backfill.", doc: "" },
    Field { name: "alarm_viewer_id_prefix", ty: "string", required: false, group: "same class of bug documented above for auto_rotate_skip/opcua_backfill.", doc: "" },
    Field { name: "alarm_viewer_show_ack", ty: "bool", required: false, group: "same class of bug documented above for auto_rotate_skip/opcua_backfill.", doc: "" },
    Field { name: "alarm_viewer_show_ts", ty: "bool", required: false, group: "same class of bug documented above for auto_rotate_skip/opcua_backfill.", doc: "" },
    Field { name: "alarm_viewer_show_empty", ty: "bool", required: false, group: "same class of bug documented above for auto_rotate_skip/opcua_backfill.", doc: "" },
    Field { name: "alarm_viewer_mode", ty: "string", required: false, group: "same class of bug documented above for auto_rotate_skip/opcua_backfill.", doc: "" },
    Field { name: "alarm_viewer_bg_color", ty: "string", required: false, group: "same class of bug documented above for auto_rotate_skip/opcua_backfill.", doc: "" },
    Field { name: "alarm_bell_id_prefix", ty: "string", required: false, group: "from day one so it doesn't repeat the alarm_viewer gap above.", doc: "" },
    Field { name: "alarm_bell_severities", ty: "any", required: false, group: "from day one so it doesn't repeat the alarm_viewer gap above.", doc: "" },
    Field { name: "alarm_bell_show_history", ty: "bool", required: false, group: "from day one so it doesn't repeat the alarm_viewer gap above.", doc: "" },
    Field { name: "alarm_bell_show_shelve", ty: "bool", required: false, group: "from day one so it doesn't repeat the alarm_viewer gap above.", doc: "" },
    Field { name: "alarm_banner_id_prefix", ty: "string", required: false, group: "mirrored from day one, same reasoning as alarm_bell above.", doc: "" },
    Field { name: "alarm_banner_severities", ty: "any", required: false, group: "mirrored from day one, same reasoning as alarm_bell above.", doc: "" },
    Field { name: "recipe_panel_id_prefix", ty: "string", required: false, group: "from day one, same reasoning as alarm_bell/alarm_banner above.", doc: "" },
    Field { name: "spark_window_s", ty: "number", required: false, group: "Sparkline (type === \"sparkline\") — same pre-existing gap as alarm_viewer above.", doc: "" },
    Field { name: "spark_color", ty: "string", required: false, group: "Sparkline (type === \"sparkline\") — same pre-existing gap as alarm_viewer above.", doc: "" },
    Field { name: "spark_stroke_width", ty: "number", required: false, group: "Sparkline (type === \"sparkline\") — same pre-existing gap as alarm_viewer above.", doc: "" },
    Field { name: "spark_fill", ty: "bool", required: false, group: "Sparkline (type === \"sparkline\") — same pre-existing gap as alarm_viewer above.", doc: "" },
    Field { name: "spark_fill_opacity", ty: "number", required: false, group: "Sparkline (type === \"sparkline\") — same pre-existing gap as alarm_viewer above.", doc: "" },
    Field { name: "spark_show_last", ty: "bool", required: false, group: "Sparkline (type === \"sparkline\") — same pre-existing gap as alarm_viewer above.", doc: "" },
    Field { name: "points", ty: "any", required: false, group: "Pipe / connector (type === \"pipe\") — same pre-existing gap.", doc: "" },
    Field { name: "routing", ty: "string", required: false, group: "Pipe / connector (type === \"pipe\") — same pre-existing gap.", doc: "" },
    Field { name: "pipe_style", ty: "string", required: false, group: "Pipe / connector (type === \"pipe\") — same pre-existing gap.", doc: "" },
    Field { name: "pipe_gradient", ty: "bool", required: false, group: "Pipe / connector (type === \"pipe\") — same pre-existing gap.", doc: "" },
    Field { name: "gradient_light_color", ty: "string", required: false, group: "Pipe / connector (type === \"pipe\") — same pre-existing gap.", doc: "" },
    Field { name: "gradient_dark_color", ty: "string", required: false, group: "Pipe / connector (type === \"pipe\") — same pre-existing gap.", doc: "" },
    Field { name: "fill_level", ty: "number", required: false, group: "Pipe / connector (type === \"pipe\") — same pre-existing gap.", doc: "" },
    Field { name: "fill_level_tag", ty: "string", required: false, group: "Pipe / connector (type === \"pipe\") — same pre-existing gap.", doc: "" },
    Field { name: "fill_level_scale", ty: "string", required: false, group: "Pipe / connector (type === \"pipe\") — same pre-existing gap.", doc: "" },
    Field { name: "fill_color", ty: "string", required: false, group: "Pipe / connector (type === \"pipe\") — same pre-existing gap.", doc: "" },
    Field { name: "fill_direction", ty: "string", required: false, group: "Pipe / connector (type === \"pipe\") — same pre-existing gap.", doc: "" },
    Field { name: "start_marker", ty: "string", required: false, group: "Pipe / connector (type === \"pipe\") — same pre-existing gap.", doc: "" },
    Field { name: "end_marker", ty: "string", required: false, group: "Pipe / connector (type === \"pipe\") — same pre-existing gap.", doc: "" },
    Field { name: "marker_size", ty: "number", required: false, group: "Pipe / connector (type === \"pipe\") — same pre-existing gap.", doc: "" },
    Field { name: "pipe_label", ty: "string", required: false, group: "Pipe / connector (type === \"pipe\") — same pre-existing gap.", doc: "" },
    Field { name: "pipe_label_tag", ty: "string", required: false, group: "Pipe / connector (type === \"pipe\") — same pre-existing gap.", doc: "" },
    Field { name: "pipe_label_format", ty: "string", required: false, group: "Pipe / connector (type === \"pipe\") — same pre-existing gap.", doc: "" },
    Field { name: "pipe_label_offset", ty: "number", required: false, group: "Pipe / connector (type === \"pipe\") — same pre-existing gap.", doc: "" },
    Field { name: "stroke_dasharray", ty: "string", required: false, group: "Pipe / connector (type === \"pipe\") — same pre-existing gap.", doc: "" },
    Field { name: "from_obj_id", ty: "string", required: false, group: "Pipe / connector (type === \"pipe\") — same pre-existing gap.", doc: "" },
    Field { name: "from_port", ty: "string", required: false, group: "Pipe / connector (type === \"pipe\") — same pre-existing gap.", doc: "" },
    Field { name: "to_obj_id", ty: "string", required: false, group: "Pipe / connector (type === \"pipe\") — same pre-existing gap.", doc: "" },
    Field { name: "to_port", ty: "string", required: false, group: "Pipe / connector (type === \"pipe\") — same pre-existing gap.", doc: "" },
    Field { name: "faceplate_id", ty: "string", required: false, group: "Faceplate instance (type === \"faceplate\") — same pre-existing gap.", doc: "" },
    Field { name: "faceplate_params", ty: "any", required: false, group: "Faceplate instance (type === \"faceplate\") — same pre-existing gap.", doc: "" },
    Field { name: "faceplate_scale", ty: "bool", required: false, group: "Faceplate instance (type === \"faceplate\") — same pre-existing gap.", doc: "" },
    Field { name: "faceplate_overrides", ty: "any", required: false, group: "Faceplate instance (type === \"faceplate\") — same pre-existing gap.", doc: "" },
    Field { name: "text_list_entries", ty: "any", required: false, group: "Text list (type === \"text_list\") — same pre-existing gap.", doc: "" },
    Field { name: "text_list_default", ty: "string", required: false, group: "Text list (type === \"text_list\") — same pre-existing gap.", doc: "" },
    Field { name: "text_list_default_color", ty: "string", required: false, group: "Text list (type === \"text_list\") — same pre-existing gap.", doc: "" },
    Field { name: "bar_series", ty: "any", required: false, group: "Bar chart (type === \"bar_chart\") — same pre-existing gap.", doc: "" },
    Field { name: "bar_orientation", ty: "string", required: false, group: "Bar chart (type === \"bar_chart\") — same pre-existing gap.", doc: "" },
    Field { name: "bar_show_values", ty: "bool", required: false, group: "Bar chart (type === \"bar_chart\") — same pre-existing gap.", doc: "" },
    Field { name: "bar_show_labels", ty: "bool", required: false, group: "Bar chart (type === \"bar_chart\") — same pre-existing gap.", doc: "" },
    Field { name: "bar_show_thresholds", ty: "bool", required: false, group: "Bar chart (type === \"bar_chart\") — same pre-existing gap.", doc: "" },
    Field { name: "bar_gap", ty: "number", required: false, group: "Bar chart (type === \"bar_chart\") — same pre-existing gap.", doc: "" },
    Field { name: "bar_y_label", ty: "string", required: false, group: "Bar chart (type === \"bar_chart\") — same pre-existing gap.", doc: "" },
    Field { name: "pie_slices", ty: "any", required: false, group: "Pie / donut chart (type === \"pie_chart\") — same pre-existing gap.", doc: "" },
    Field { name: "pie_mode", ty: "string", required: false, group: "Pie / donut chart (type === \"pie_chart\") — same pre-existing gap.", doc: "" },
    Field { name: "pie_inner_ratio", ty: "number", required: false, group: "Pie / donut chart (type === \"pie_chart\") — same pre-existing gap.", doc: "" },
    Field { name: "pie_show_labels", ty: "bool", required: false, group: "Pie / donut chart (type === \"pie_chart\") — same pre-existing gap.", doc: "" },
    Field { name: "pie_center_text", ty: "string", required: false, group: "Pie / donut chart (type === \"pie_chart\") — same pre-existing gap.", doc: "" },
    Field { name: "pie_center_tag", ty: "string", required: false, group: "Pie / donut chart (type === \"pie_chart\") — same pre-existing gap.", doc: "" },
    Field { name: "pie_center_format", ty: "string", required: false, group: "Pie / donut chart (type === \"pie_chart\") — same pre-existing gap.", doc: "" },
    Field { name: "pie_show_legend", ty: "bool", required: false, group: "Pie / donut chart (type === \"pie_chart\") — same pre-existing gap.", doc: "" },
    Field { name: "target_lang", ty: "string", required: false, group: "Language selector (type === \"lang_selector\") — same pre-existing gap.", doc: "" },
];

/// I campi di una pagina sinottica.
pub const PAGE_FIELDS: &[Field] = &[
    Field { name: "id", ty: "string", required: true, group: "", doc: "" },
    Field { name: "name", ty: "string", required: true, group: "", doc: "" },
    Field { name: "objects", ty: "SynopticObject[]", required: false, group: "", doc: "" },
    Field { name: "background", ty: "string", required: false, group: "", doc: "" },
    Field { name: "background_dark", ty: "string", required: false, group: "", doc: "Dark-theme override of `background`. Same drop-on-round-trip gap as `auto_rotate_skip` below — found during a systematic TS↔Rust field audit, not from a specific bug report." },
    Field { name: "width", ty: "number", required: false, group: "", doc: "" },
    Field { name: "height", ty: "number", required: false, group: "", doc: "" },
    Field { name: "groups", ty: "any", required: false, group: "", doc: "" },
    Field { name: "zones", ty: "string[]", required: false, group: "", doc: "Zone restriction: if set, only users whose `allowed_zones` intersects this list can view or load this page. Empty list or None = accessible to all." },
    Field { name: "auto_rotate_skip", ty: "bool", required: false, group: "", doc: "When true, this page is skipped by the kiosk auto-rotate cycle. Was missing from this mirror (pre-existing gap: GET /api/synoptics/:name deserializes through this struct and would silently drop it on round-trip) — added here alongside `locked` since both are read via the same endpoint." },
    Field { name: "locked", ty: "bool", required: false, group: "", doc: "When true, the page is read-only in the editor (no object/property edits). Does not block duplicate/delete (already confirm-gated separately)." },
];

/// I campi di una definizione di tag (da sws-core/src/project.rs).
pub const TAG_FIELDS: &[Field] = &[
    Field { name: "id", ty: "string", required: true, group: "", doc: "" },
    Field { name: "description", ty: "string", required: false, group: "", doc: "" },
    Field { name: "data_type", ty: "string", required: false, group: "", doc: "Storage type for this tag: \"bool\", \"int\", \"float\", or \"string\". Drives the initial `TagValue` variant seeded into the TagDb at startup." },
    Field { name: "history", ty: "bool", required: false, group: "", doc: "When true, tag samples are persisted to `datastore_id` (or the project default datastore when unset). Default false." },
    Field { name: "datastore_id", ty: "string", required: false, group: "", doc: "Which datastore (by `DatastoreConfig::id`) receives this tag's samples. When None and `history` is true, uses the first configured datastore (or the built-in SQLite fallback)." },
    Field { name: "history_deadband", ty: "number", required: false, group: "", doc: "Minimum absolute change required to record a new sample. Prevents chatty analog tags from flooding the datastore with near-identical values." },
    Field { name: "history_min_interval_ms", ty: "number", required: false, group: "", doc: "Minimum time between recorded samples (ms). Even if the value changed, samples closer than this interval are dropped." },
    Field { name: "expression", ty: "string", required: false, group: "", doc: "Python expression evaluated against a `tags` dict snapshot of the current TagDb values.  Example: `tags[\"motor.v\"] * tags[\"motor.i\"]`. When set the tag is read-only; writes via the API or TagWriteBus are rejected.  The expression is re-evaluated whenever any tag in the project changes." },
    Field { name: "unit", ty: "string", required: false, group: "possibile); prima erano ridichiarati su ogni oggetto e divergevano.", doc: "Unità di misura ingegneristica (es. \"°C\", \"bar\"). Solo display." },
    Field { name: "decimals", ty: "number", required: false, group: "possibile); prima erano ridichiarati su ogni oggetto e divergevano.", doc: "Cifre decimali di default per la visualizzazione." },
    Field { name: "raw_min", ty: "number", required: false, group: "possibile); prima erano ridichiarati su ogni oggetto e divergevano.", doc: "Scaling lineare raw→eng applicato all'INGESTIONE (`TagDb::ingest`, usato dai plugin di protocollo) e invertito sulle scritture verso il device. Vanno impostati tutti e quattro; con `raw_min == raw_max` lo scaling è ignorato. Gli altri produttori (script, tag derivati, API su tag virtuali) passano da `set()` e NON vengono scalati: producono già valori ingegneristici." },
    Field { name: "raw_max", ty: "number", required: false, group: "possibile); prima erano ridichiarati su ogni oggetto e divergevano.", doc: "" },
    Field { name: "eng_min", ty: "number", required: false, group: "possibile); prima erano ridichiarati su ogni oggetto e divergevano.", doc: "" },
    Field { name: "eng_max", ty: "number", required: false, group: "possibile); prima erano ridichiarati su ogni oggetto e divergevano.", doc: "" },
    Field { name: "range_lo", ty: "number", required: false, group: "possibile); prima erano ridichiarati su ogni oggetto e divergevano.", doc: "Range di visualizzazione di default per i widget (gauge, barre, trend)." },
    Field { name: "range_hi", ty: "number", required: false, group: "possibile); prima erano ridichiarati su ogni oggetto e divergevano.", doc: "" },
    Field { name: "write_min_role", ty: "string", required: false, group: "possibile); prima erano ridichiarati su ogni oggetto e divergevano.", doc: "Ruolo minimo per SCRIVERE questo tag via API/WS (F3.1). È l'enforcement che il server può davvero garantire — il min_role degli oggetti è UX. Valori: \"Viewer\" | \"Operator\" | \"Supervisor\" | \"Admin\". Assente = regola storica (Operator+ su ogni scrittura)." },
    Field { name: "limit_lo_lo", ty: "number", required: false, group: "possibile); prima erano ridichiarati su ogni oggetto e divergevano.", doc: "Limiti ingegneristici: default per le soglie visive dei widget (lo_lo/lo → alarm_low/warn_low, hi/hi_hi → warn_high/alarm_high)." },
    Field { name: "limit_lo", ty: "number", required: false, group: "possibile); prima erano ridichiarati su ogni oggetto e divergevano.", doc: "" },
    Field { name: "limit_hi", ty: "number", required: false, group: "possibile); prima erano ridichiarati su ogni oggetto e divergevano.", doc: "" },
    Field { name: "limit_hi_hi", ty: "number", required: false, group: "possibile); prima erano ridichiarati su ogni oggetto e divergevano.", doc: "" },
];

/// Tutti i tipi di oggetto che l'editor sa creare (dalla union TS).
pub const OBJECT_TYPES: &[&str] = &[
    "rect",
    "ellipse",
    "line",
    "text",
    "image",
    "button",
    "navbutton",
    "checkbox",
    "radio",
    "slider",
    "setpoint",
    "gauge",
    "led",
    "state_lamp",
    "progress_bar",
    "table",
    "trend",
    "text_list",
    "bar_chart",
    "pie_chart",
    "sparkline",
    "kpi_tile",
    "data_log",
    "alarm_viewer",
    "alarm_bell",
    "alarm_banner",
    "alarm_history",
    "recipe_panel",
    "symbol",
    "pipe",
    "xy_plot",
    "grid",
    "faceplate",
    "lang_selector",
    "lang_button",
];

/// Campi il cui valore è scelto da un insieme chiuso: `(campo, valori)`.
pub const FIELD_ENUMS: &[(&str, &[&str])] = &[
    ("alarm_viewer_mode", &["list", "banner", "table"]),
    ("bar_mode", &["grouped", "stacked"]),
    ("bar_orientation", &["vertical", "horizontal"]),
    ("blink_mode", &["always", "tag", "alarm"]),
    ("button_mode", &["write", "momentary", "toggle", "set", "reset", "increment", "decrement"]),
    ("end_marker", &["none", "arrow", "dot", "flange"]),
    ("fill_direction", &["start-to-end", "end-to-start"]),
    ("fill_gradient", &["vertical", "horizontal", "radial"]),
    ("fill_level_scale", &["0-1", "0-100"]),
    ("font_style", &["normal", "italic"]),
    ("from_port", &["top", "bottom", "left", "right", "center"]),
    ("image_fit", &["stretch", "contain", "cover"]),
    ("led_shape", &["circle", "square", "triangle"]),
    ("min_role", &["Viewer", "Operator", "Supervisor", "Admin"]),
    ("min_role_effect", &["hide", "disable"]),
    ("motion_anchor", &["center", "top_left"]),
    ("orientation", &["horizontal", "vertical"]),
    ("pie_label_mode", &["percent", "value", "value_percent", "label_percent"]),
    ("pie_mode", &["pie", "donut"]),
    ("pipe_style", &["flat", "tube", "wire"]),
    ("routing", &["straight", "orthogonal", "diagonal", "bezier"]),
    ("start_marker", &["none", "arrow", "dot", "flange"]),
    ("symbol_id", &["agitator", "battery", "blower", "boiler", "breaker", "check_valve", "chiller", "column", "compressor", "conveyor", "cooling_tower", "cyclone", "fan", "filter", "flow_meter", "furnace", "garage", "heat_exchanger", "heat_pump", "home_lightning", "level_sensor", "mixer", "motor", "pressure_indicator", "pump", "reactor", "relief_valve", "roller_shade", "separator", "silo", "solar_panel", "strainer", "tank", "temperature_sensor", "transmission_tower", "valve", "valve_3way", "valve_motorized", "valve_pneumatic", "window_open"]),
    ("symbol_spin", &["always", "on_state", "tag"]),
    ("text_anchor", &["start", "middle", "end"]),
    ("text_valign", &["top", "middle", "bottom"]),
    ("to_port", &["top", "bottom", "left", "right", "center"]),
    ("trend_dt_date_order", &["dmy", "mdy", "ymd"]),
    ("trend_dt_separator", &["-", "/", "."]),
    ("trend_dt_time_format", &["24h", "12h"]),
];

/// I `kind` di sorgente e i campi di ciascuna configurazione.
pub const SOURCE_KINDS: &[&str] = &[
    "modbus_tcp",
    "modbus_rtu",
    "opcua_server",
    "mqtt",
    "opcua_client",
    "homeassistant",
    "s7",
    "enip",
];

pub const SOURCE_FIELDS: &[(&str, &[Field])] = &[
    ("modbus_tcp", SOURCE_MODBUS_TCP_FIELDS),
    ("modbus_rtu", SOURCE_MODBUS_RTU_FIELDS),
    ("opcua_server", SOURCE_OPCUA_SERVER_FIELDS),
    ("mqtt", SOURCE_MQTT_FIELDS),
    ("opcua_client", SOURCE_OPCUA_CLIENT_FIELDS),
    ("homeassistant", SOURCE_HOMEASSISTANT_FIELDS),
    ("s7", SOURCE_S7_FIELDS),
    ("enip", SOURCE_ENIP_FIELDS),
];

/// Campi della sorgente `modbus_tcp` (ModbusTcpConfig).
pub const SOURCE_MODBUS_TCP_FIELDS: &[Field] = &[
    Field { name: "id", ty: "string", required: true, group: "", doc: "" },
    Field { name: "host", ty: "string", required: true, group: "", doc: "" },
    Field { name: "port", ty: "number", required: false, group: "", doc: "" },
    Field { name: "unit_id", ty: "number", required: false, group: "", doc: "" },
    Field { name: "poll_interval_ms", ty: "number", required: false, group: "", doc: "How often to poll all registers, in milliseconds." },
    Field { name: "registers", ty: "RegisterMapping[]", required: true, group: "", doc: "" },
];

/// Campi di `RegisterMapping`, usato dentro la sorgente `modbus_tcp`.
pub const SOURCE_MODBUS_TCP_REGISTERMAPPING_FIELDS: &[Field] = &[
    Field { name: "tag", ty: "string", required: true, group: "", doc: "TagId to write the value into." },
    Field { name: "address", ty: "number", required: true, group: "", doc: "Holding register start address (0-based)." },
    Field { name: "scale", ty: "number", required: false, group: "", doc: "Multiply the raw u16 word by this before storing. Default 1.0." },
];

/// Campi della sorgente `modbus_rtu` (ModbusRtuConfig).
pub const SOURCE_MODBUS_RTU_FIELDS: &[Field] = &[
    Field { name: "id", ty: "string", required: true, group: "", doc: "" },
    Field { name: "device", ty: "string", required: true, group: "", doc: "Serial device path, e.g. `/dev/ttyS0` or `/dev/ttyUSB0`." },
    Field { name: "baud_rate", ty: "number", required: false, group: "", doc: "Baud rate, e.g. 9600, 19200, 115200." },
    Field { name: "parity", ty: "string", required: false, group: "", doc: "Parity: \"N\" (none), \"E\" (even), \"O\" (odd). Default \"N\"." },
    Field { name: "data_bits", ty: "number", required: false, group: "", doc: "Data bits: 7 or 8. Default 8." },
    Field { name: "stop_bits", ty: "number", required: false, group: "", doc: "Stop bits: 1 or 2. Default 1." },
    Field { name: "unit_id", ty: "number", required: false, group: "", doc: "" },
    Field { name: "poll_interval_ms", ty: "number", required: false, group: "", doc: "" },
    Field { name: "registers", ty: "RegisterMapping[]", required: true, group: "", doc: "" },
];

/// Campi di `RegisterMapping`, usato dentro la sorgente `modbus_rtu`.
pub const SOURCE_MODBUS_RTU_REGISTERMAPPING_FIELDS: &[Field] = &[
    Field { name: "tag", ty: "string", required: true, group: "", doc: "TagId to write the value into." },
    Field { name: "address", ty: "number", required: true, group: "", doc: "Holding register start address (0-based)." },
    Field { name: "scale", ty: "number", required: false, group: "", doc: "Multiply the raw u16 word by this before storing. Default 1.0." },
];

/// Campi della sorgente `opcua_server` (OpcUaServerConfig).
pub const SOURCE_OPCUA_SERVER_FIELDS: &[Field] = &[
    Field { name: "id", ty: "string", required: true, group: "", doc: "" },
    Field { name: "port", ty: "number", required: false, group: "", doc: "TCP port to listen on. Default 4840 (OPC-UA standard)." },
    Field { name: "namespace_uri", ty: "string", required: false, group: "", doc: "Namespace URI for the SWS nodes, e.g. `urn:soligolab:sws`. Default `urn:soligolab:sws`." },
    Field { name: "nodes", ty: "OpcUaServerNodeMapping[]", required: false, group: "", doc: "Tag → OPC-UA node mappings. `node_id` is the string identifier within the SWS namespace (e.g. `\"pump1.speed\"`)." },
];

/// Campi di `OpcUaServerNodeMapping`, usato dentro la sorgente `opcua_server`.
pub const SOURCE_OPCUA_SERVER_OPCUASERVERNODEMAPPING_FIELDS: &[Field] = &[
    Field { name: "tag", ty: "string", required: true, group: "", doc: "SWS tag identifier." },
    Field { name: "node_id", ty: "string", required: false, group: "", doc: "OPC-UA string node id within the server namespace. Defaults to the tag id when omitted." },
];

/// Campi della sorgente `mqtt` (MqttConfig).
pub const SOURCE_MQTT_FIELDS: &[Field] = &[
    Field { name: "id", ty: "string", required: true, group: "", doc: "" },
    Field { name: "host", ty: "string", required: true, group: "", doc: "" },
    Field { name: "port", ty: "number", required: false, group: "", doc: "" },
    Field { name: "client_id", ty: "string", required: false, group: "", doc: "" },
    Field { name: "topics", ty: "TopicMapping[]", required: true, group: "", doc: "" },
    Field { name: "username", ty: "string", required: false, group: "Authentication", doc: "Plain-text password. Sits in `project.yaml` on disk — for production use `password_env` instead. The web layer masks this on GET responses." },
    Field { name: "password", ty: "string", required: false, group: "Authentication", doc: "" },
    Field { name: "password_env", ty: "string", required: false, group: "Authentication", doc: "Environment variable to read the password from at runtime. Wins over `password` when both are set, so secrets stay out of the YAML." },
    Field { name: "keep_alive_secs", ty: "number", required: false, group: "Connection tuning", doc: "MQTT keep-alive interval in seconds. Default 10." },
    Field { name: "clean_session", ty: "bool", required: false, group: "Connection tuning", doc: "`false` keeps the broker-side session across reconnects. Default true." },
    Field { name: "qos", ty: "number", required: false, group: "Connection tuning", doc: "QoS for subscribes/publishes when the per-topic field is unset. Accepts 0 / 1 / 2; anything else falls back to 0." },
    Field { name: "tls", ty: "MqttTlsConfig", required: false, group: "Connection tuning", doc: "TLS settings. Absent / `enabled: false` → plain TCP." },
    Field { name: "last_will", ty: "MqttLastWill", required: false, group: "Connection tuning", doc: "Last-will message published by the broker on ungraceful disconnect." },
    Field { name: "sparkplug", ty: "SparkplugConfig", required: false, group: "Connection tuning", doc: "When set, this source operates in Sparkplug B mode: payloads are protobuf-encoded and topics follow `spBv1.0/{group_id}/...`. Regular `topics` mapping is ignored when this is present." },
    Field { name: "random_client_id", ty: "RandomClientId", required: false, group: "Connection tuning", doc: "When enabled, the runtime derives the wire client_id by gluing an instance-specific id to `client_id` (used as a prefix/suffix label) instead of using `client_id` literally. Avoids collisions when the same project is opened from the IDE and/or deployed to several devices against the same broker — each instance would otherwise connect with the exact same client_id and keep kicking each other." },
    Field { name: "max_silence_secs", ty: "number", required: false, group: "Connection tuning", doc: "Opt-in staleness guard: if no tag owned by this source updates within this many seconds, the watchdog in `SourceSupervisor` restarts it — independent of any error from the MQTT client, which may report \"connected\" even when a stuck/half-open session stops producing data. Off by default: MQTT is push-based with no natural reporting interval, so a guessed default would risk restarting sources that are legitimately just quiet." },
];

/// Campi di `TopicMapping`, usato dentro la sorgente `mqtt`.
pub const SOURCE_MQTT_TOPICMAPPING_FIELDS: &[Field] = &[
    Field { name: "tag", ty: "string", required: true, group: "", doc: "TagId to write the value into." },
    Field { name: "topic", ty: "string", required: true, group: "", doc: "MQTT topic to subscribe to (exact match; wildcards not handled in PoC)." },
    Field { name: "json_path", ty: "string", required: false, group: "", doc: "Optional dot-separated JSON path. If set, the payload is parsed as JSON and the field at `json_path` is extracted (e.g. \"temperature\" → root.temperature)." },
    Field { name: "publish_topic", ty: "string", required: false, group: "", doc: "Optional outbound topic. When set, a `PUT /api/tags/:id` for `tag` is forwarded to this topic as a raw string payload (`true` / `42.5` / `…`). If equal to `topic`, the same channel is used for read and write." },
    Field { name: "qos", ty: "number", required: false, group: "", doc: "Per-mapping QoS override (0 / 1 / 2). When absent, the source-level `MqttConfig::qos` is used, then 0 as the final fallback." },
];

/// Campi della sorgente `opcua_client` (OpcUaClientConfig).
pub const SOURCE_OPCUA_CLIENT_FIELDS: &[Field] = &[
    Field { name: "id", ty: "string", required: true, group: "", doc: "" },
    Field { name: "endpoint_url", ty: "string", required: true, group: "", doc: "e.g. `opc.tcp://192.168.1.100:4840`." },
    Field { name: "security_policy", ty: "string", required: false, group: "", doc: "PoC: only \"None\" is wired end-to-end; the field exists so the project format doesn't need a migration when we wire the rest." },
    Field { name: "auth", ty: "OpcUaAuth", required: false, group: "", doc: "" },
    Field { name: "subscription_interval_ms", ty: "number", required: false, group: "", doc: "Server-side subscription publishing interval, in milliseconds." },
    Field { name: "nodes", ty: "OpcUaNodeMapping[]", required: false, group: "", doc: "Nodes to subscribe to. NodeId format is the canonical OPC-UA one, e.g. `ns=2;s=Machine.CycleTime` or `ns=0;i=2253`." },
    Field { name: "trust_all_certs", ty: "bool", required: false, group: "", doc: "When true (default), any server certificate is automatically trusted. Set to false to require explicit certificate approval via the trust store." },
];

/// Campi di `OpcUaNodeMapping`, usato dentro la sorgente `opcua_client`.
pub const SOURCE_OPCUA_CLIENT_OPCUANODEMAPPING_FIELDS: &[Field] = &[
    Field { name: "tag", ty: "string", required: true, group: "", doc: "" },
    Field { name: "node_id", ty: "string", required: true, group: "", doc: "" },
    Field { name: "description", ty: "string", required: false, group: "", doc: "" },
];

/// Campi della sorgente `homeassistant` (HomeAssistantConfig).
pub const SOURCE_HOMEASSISTANT_FIELDS: &[Field] = &[
    Field { name: "id", ty: "string", required: true, group: "", doc: "" },
    Field { name: "url", ty: "string", required: true, group: "", doc: "Base URL of the HA instance, e.g. `http://homeassistant.local:8123`." },
    Field { name: "token", ty: "string", required: false, group: "", doc: "Long-lived access token (plain text). Use `token_env` in production." },
    Field { name: "token_env", ty: "string", required: false, group: "", doc: "Environment variable to read the access token from at runtime. Wins over `token` when both are set." },
    Field { name: "entities", ty: "EntityMapping[]", required: true, group: "", doc: "" },
];

/// Campi di `EntityMapping`, usato dentro la sorgente `homeassistant`.
pub const SOURCE_HOMEASSISTANT_ENTITYMAPPING_FIELDS: &[Field] = &[
    Field { name: "tag", ty: "string", required: true, group: "", doc: "SWS tag id to write values into." },
    Field { name: "entity_id", ty: "string", required: true, group: "", doc: "HA entity id, e.g. `sensor.living_room_temperature`." },
    Field { name: "attribute", ty: "string", required: false, group: "", doc: "When set, read this attribute instead of the entity's main `state`." },
    Field { name: "write_domain", ty: "string", required: false, group: "", doc: "HA service domain for write-back (e.g. `light`, `switch`, `input_number`). When absent the tag is read-only." },
    Field { name: "write_service", ty: "string", required: false, group: "", doc: "HA service name for write-back (e.g. `turn_on`, `set_value`)." },
];

/// Campi della sorgente `s7` (S7Config).
pub const SOURCE_S7_FIELDS: &[Field] = &[
    Field { name: "id", ty: "string", required: true, group: "", doc: "" },
    Field { name: "ip", ty: "string", required: true, group: "", doc: "PLC IP address." },
    Field { name: "rack", ty: "number", required: false, group: "", doc: "CPU rack number. Usually 0." },
    Field { name: "slot", ty: "number", required: false, group: "", doc: "CPU slot number. 1 for S7-300/400, 0 for S7-1200/1500." },
    Field { name: "poll_interval_ms", ty: "number", required: false, group: "", doc: "Poll interval in milliseconds." },
    Field { name: "tags", ty: "S7TagMapping[]", required: false, group: "", doc: "" },
];

/// Campi di `S7TagMapping`, usato dentro la sorgente `s7`.
pub const SOURCE_S7_S7TAGMAPPING_FIELDS: &[Field] = &[
    Field { name: "tag", ty: "string", required: true, group: "", doc: "SWS tag id." },
    Field { name: "area", ty: "string", required: false, group: "", doc: "Memory area: \"db\", \"m\" (Merker), \"i\" (inputs), \"q\" (outputs)." },
    Field { name: "db_num", ty: "number", required: false, group: "", doc: "Data Block number (only for area == \"db\")." },
    Field { name: "byte_offset", ty: "number", required: true, group: "", doc: "Byte offset within the area/DB." },
    Field { name: "bit_offset", ty: "number", required: false, group: "", doc: "Bit offset within the byte (0-7). Only used for `data_type: bool`." },
    Field { name: "data_type", ty: "S7DataType", required: false, group: "", doc: "Data type of this tag at the PLC." },
    Field { name: "writable", ty: "bool", required: false, group: "", doc: "Optional write-back: when true, `PUT /api/tags/:id` writes back to PLC." },
];

/// Campi della sorgente `enip` (EnIpConfig).
pub const SOURCE_ENIP_FIELDS: &[Field] = &[
    Field { name: "id", ty: "string", required: true, group: "", doc: "" },
    Field { name: "ip", ty: "string", required: true, group: "", doc: "PLC IP address (port 44818 is implied)." },
    Field { name: "slot", ty: "number", required: false, group: "", doc: "CIP slot number (rack/slot for ControlLogix; 0 for CompactLogix/Micro)." },
    Field { name: "poll_interval_ms", ty: "number", required: false, group: "", doc: "Poll interval in milliseconds." },
    Field { name: "tags", ty: "EnIpTagMapping[]", required: false, group: "", doc: "" },
];

/// Campi di `EnIpTagMapping`, usato dentro la sorgente `enip`.
pub const SOURCE_ENIP_ENIPTAGMAPPING_FIELDS: &[Field] = &[
    Field { name: "tag", ty: "string", required: true, group: "", doc: "SWS tag id." },
    Field { name: "plc_tag", ty: "string", required: true, group: "", doc: "PLC tag name (e.g. \"Motor_Speed\" or \"Program:MainProgram.Counter\")." },
    Field { name: "data_type", ty: "EnIpDataType", required: false, group: "", doc: "CIP data type of this PLC tag." },
    Field { name: "writable", ty: "bool", required: false, group: "", doc: "When true, `PUT /api/tags/:id` writes back to the PLC." },
];

/// Campi effettivamente usati per tipo, misurati sui template.
pub const TYPE_USAGE: &[(&str, &[&str])] = &[
    ("alarm_banner", &["height", "id", "type", "width", "x", "y"]),
    ("alarm_bell", &["alarm_bell_show_history", "alarm_bell_show_shelve", "height", "id", "type", "width", "x", "y"]),
    ("alarm_history", &["alarm_viewer_max_rows", "height", "id", "type", "width", "x", "y"]),
    ("alarm_viewer", &["alarm_viewer_max_rows", "alarm_viewer_show_ack", "height", "id", "type", "width", "x", "y"]),
    ("bar_chart", &["alarm_high", "bar_series", "bar_show_thresholds", "height", "id", "type", "warn_high", "width", "x", "y"]),
    ("button", &["confirm_message", "fill", "height", "id", "label", "require_confirm", "tag", "type", "width", "write_value", "x", "y"]),
    ("checkbox", &["height", "id", "label", "tag", "type", "width", "x", "y"]),
    ("data_log", &["datalog_page_size", "height", "id", "tag", "type", "width", "x", "y"]),
    ("ellipse", &["bindings", "fill", "height", "id", "motion_max", "motion_min", "motion_path", "motion_tag", "stroke", "stroke_width", "type", "width", "x", "y"]),
    ("faceplate", &["faceplate_id", "faceplate_params", "height", "id", "type", "width", "x", "y"]),
    ("gauge", &["alarm_high", "alarm_low", "height", "id", "label", "max", "min", "tag", "transition_duration_ms", "type", "unit", "warn_high", "warn_low", "width", "x", "y"]),
    ("grid", &["grid_border_color", "grid_cells", "grid_cols", "grid_rows", "grid_show_borders", "height", "id", "type", "width", "x", "y"]),
    ("image", &["height", "id", "src", "type", "width", "x", "y"]),
    ("kpi_tile", &["height", "id", "label", "tag", "type", "unit", "width", "x", "y"]),
    ("lang_button", &["height", "id", "label", "target_lang", "type", "width", "x", "y"]),
    ("lang_selector", &["height", "id", "type", "width", "x", "y"]),
    ("led", &["height", "id", "off_color", "on_color", "on_value", "tag", "type", "width", "x", "y"]),
    ("line", &["height", "id", "stroke", "stroke_width", "type", "width", "x", "x2", "y", "y2"]),
    ("navbutton", &["fill", "group_id", "height", "id", "label", "locked", "target_page", "type", "width", "x", "y"]),
    ("pie_chart", &["decimals", "height", "id", "pie_center_format", "pie_center_tag", "pie_group_below_pct", "pie_group_color", "pie_group_label", "pie_hole_color", "pie_inner_ratio", "pie_label_mode", "pie_mode", "pie_show_labels", "pie_slices", "type", "width", "x", "y"]),
    ("pipe", &["fill_color", "fill_level_scale", "fill_level_tag", "from_obj_id", "from_port", "height", "id", "points", "routing", "stroke", "stroke_width", "to_obj_id", "to_port", "type", "width", "x", "y"]),
    ("progress_bar", &["alarm_low", "background", "fill", "height", "id", "max", "min", "tag", "type", "warn_low", "width", "x", "y"]),
    ("radio", &["height", "id", "options", "tag", "type", "width", "x", "y"]),
    ("recipe_panel", &["height", "id", "type", "width", "x", "y"]),
    ("rect", &["bindings", "blink_mode", "blink_rate_ms", "blink_tag", "corner_radius", "fill", "height", "id", "opacity", "rx", "stroke", "stroke_width", "transition_duration_ms", "type", "width", "x", "y", "z_index"]),
    ("setpoint", &["height", "id", "label", "max", "min", "step", "tag", "type", "width", "x", "y"]),
    ("slider", &["fill", "height", "id", "max", "min", "show_value", "step", "tag", "type", "unit", "width", "x", "y"]),
    ("sparkline", &["height", "id", "spark_color", "spark_window_s", "tag", "type", "width", "x", "y"]),
    ("state_lamp", &["height", "id", "tag", "text_list_entries", "type", "width", "x", "y"]),
    ("symbol", &["height", "id", "name", "state_alarm_color", "state_off_color", "state_on_color", "state_tag", "symbol_id", "symbol_spin", "symbol_spin_s", "symbol_spin_tag", "symbol_states", "transition_duration_ms", "type", "width", "x", "y"]),
    ("table", &["height", "id", "label", "table_rows", "type", "width", "x", "y"]),
    ("text", &["bad_value_style", "color", "font_size", "font_weight", "format", "group_id", "height", "id", "line_height", "locked", "quality_dot", "show_alarm_state", "stale_after_s", "tag", "text", "text_anchor", "text_valign", "text_wrap", "transition_duration_ms", "type", "width", "x", "y"]),
    ("text_list", &["height", "id", "tag", "text_list_default", "text_list_default_color", "text_list_entries", "type", "width", "x", "y"]),
    ("trend", &["extra_tags", "height", "id", "line_color", "tag", "trend_tags", "type", "width", "window_s", "x", "y"]),
    ("xy_plot", &["height", "id", "tag", "type", "width", "x", "xy_trail_s", "xy_x_max", "xy_x_min", "xy_y_max", "xy_y_min", "y", "y_tag"]),
];

/// Un esempio YAML reale per tipo, preso dal template che lo usa meglio.
pub const TYPE_EXAMPLES: &[(&str, &str)] = &[
    ("alarm_banner", "id: cl1_alarm_banner\ntype: alarm_banner\nx: 20.0\ny: 590.0\nwidth: 760.0\nheight: 70.0"),
    ("alarm_bell", "id: cl1_alarm_bell\ntype: alarm_bell\nx: 20.0\ny: 536.0\nwidth: 130.0\nheight: 34.0\nalarm_bell_show_history: true\nalarm_bell_show_shelve: true"),
    ("alarm_history", "id: o_history\ntype: alarm_history\nx: 650.0\ny: 182.0\nwidth: 600.0\nheight: 250.0\nalarm_viewer_max_rows: 6.0"),
    ("alarm_viewer", "id: o_viewer\ntype: alarm_viewer\nx: 30.0\ny: 182.0\nwidth: 600.0\nheight: 250.0\nalarm_viewer_max_rows: 6.0\nalarm_viewer_show_ack: true"),
    ("bar_chart", "id: o_bar\ntype: bar_chart\nx: 30.0\ny: 388.0\nwidth: 290.0\nheight: 220.0\nbar_series:\n- tag: demo.sim.bar_a\n  label: A\n  color: '#0ea5e9'\n- tag: demo.sim.bar_b\n  label: B\n  color: '#22c55e'\n- tag: demo.sim.bar_c\n  label: C\n  color: '#f59e0b'\nwarn_high: 70.0\nalarm_high: 90.0\nbar_show_thresholds: true"),
    ("button", "id: o_button\ntype: button\nx: 30.0\ny: 254.0\nwidth: 260.0\nheight: 46.0\nlabel: Avvia (chiede conferma)\nfill: '#2563eb'\ntag: demo.cmd.button\nwrite_value: true\nrequire_confirm: true\nconfirm_message: Questo comando avvia l'impianto."),
    ("checkbox", "id: o_checkbox\ntype: checkbox\nx: 340.0\ny: 258.0\nwidth: 250.0\nheight: 32.0\nlabel: Abilitato\ntag: demo.cmd.enable"),
    ("data_log", "id: o_datalog\ntype: data_log\nx: 30.0\ny: 442.0\nwidth: 600.0\nheight: 320.0\ntag: demo.sim.pressure\ndatalog_page_size: 12.0"),
    ("ellipse", "id: o_motion\ntype: ellipse\nx: 250.0\ny: 550.0\nwidth: 20.0\nheight: 20.0\nfill: '#f59e0b'\nstroke: '#fbbf24'\nstroke_width: 2.0\nmotion_tag: demo.sim.ramp\nmotion_min: 0.0\nmotion_max: 100.0\nmotion_path:\n- x: 260.0\n  y: 560.0\n- x: 430.0\n  y: 505.0\n- x: 600.0\n  y: 560.0"),
    ("faceplate", "id: o_faceplate\ntype: faceplate\nx: 30.0\ny: 474.0\nwidth: 290.0\nheight: 150.0\nfaceplate_id: motor_basic\nfaceplate_params:\n  tag_prefix: demo.sim.motor\n  label: Motore demo"),
    ("gauge", "id: cl2_soc_gauge\ntype: gauge\nx: 310\ny: 160\nwidth: 200\nheight: 160\ntag: solar.battery_soc\nmin: 0\nmax: 100\nunit: '%'\nlabel: '{{soc_batteria}}'\nwarn_low: 20\nalarm_low: 10"),
    ("grid", "id: o_grid\ntype: grid\nx: 960.0\ny: 388.0\nwidth: 290.0\nheight: 220.0\ngrid_rows: 2\ngrid_cols: 2\ngrid_show_borders: true\ngrid_border_color: '#334155'\ngrid_cells:\n- row: 0\n  col: 0\n  child:\n    id: g_led\n    type: led\n    x: 20.0\n    y: 20.0\n    width: 40.0\n    height: 40.0\n    tag: demo.sim.running\n    on_color: '#22c55e'\n    off_color: '#334155'\n    on_value: 'true'\n- row: 0\n  col: 1\n  child:\n    id: g_text\n    type: text\n    x: 10.0\n    y: 30.0\n    width: 120.0\n    height: 24.0\n    tag: demo.sim.counter\n    format: '%d'\n    font_size: 18.0\n    color: '#e2e8f0'\n- row: 1\n  col: 0\n  child:\n    id: g_rect\n    type: rect\n    x: 15.0\n    y: 20.0\n    width: 110.0\n    height: 45.0\n    fill: '#0ea5e9'\n- row: 1\n  col: 1\n  child:\n    id: g_lamp\n    type: state_lamp\n    x: 15.0\n    y: 22.0\n    width: 100.0\n    height: 40.0\n    tag: demo.sim.mode\n    text_list_entries:\n    - value: Auto\n      label: A\n      color: '#22c55e'\n    - value: Manuale\n      label: M\n      color: '#f59e0b'\n    - value: Fermo\n      label: F\n      color: '#64748b'"),
    ("image", "id: cl1_pv_icon\ntype: image\nx: 88\ny: 96\nwidth: 28\nheight: 28\nsrc: /symbols/solar-panel.svg"),
    ("kpi_tile", "id: o_kpi\ntype: kpi_tile\nx: 30.0\ny: 542.0\nwidth: 290.0\nheight: 110.0\nlabel: Pressione\ntag: demo.sim.pressure\nunit: bar"),
    ("lang_button", "id: o_langbtn_it\ntype: lang_button\nx: 960.0\ny: 202.0\nwidth: 90.0\nheight: 36.0\nlabel: IT\ntarget_lang: it"),
    ("lang_selector", "id: lang_sel_auto\ntype: lang_selector\nx: 702\ny: 8\nwidth: 90\nheight: 26"),
    ("led", "id: cl1_pv_led\ntype: led\nx: 248\ny: 96\nwidth: 14\nheight: 14\ntag: solar.pv_power\non_value: 0.05\non_color: '#f59e0b'\noff_color: '#374151'"),
    ("line", "id: cl1_line_pv_casa\ntype: line\nx: 270\ny: 140\nx2: 300\ny2: 140\nstroke: '#f59e0b'\nstroke_width: 2"),
    ("navbutton", "id: nav1\ntype: navbutton\nx: 660.0\ny: 12.0\nwidth: 144.0\nheight: 32.0\nlabel: 1. Base\ntarget_page: demo_p1\nfill: '#334155'\ngroup_id: nav\nlocked: true"),
    ("pie_chart", "id: o_pie\ntype: pie_chart\nx: 340.0\ny: 388.0\nwidth: 250.0\nheight: 220.0\npie_mode: donut\npie_inner_ratio: 0.55\npie_slices:\n- tag: demo.sim.pie_a\n  label: Uno\n  color: '#0ea5e9'\n- tag: demo.sim.pie_b\n  label: Due\n  color: '#22c55e'\n- tag: demo.sim.pie_c\n  label: Tre\n  color: '#f59e0b'\npie_show_labels: true\npie_label_mode: label_percent\npie_hole_color: '#0f172a'\npie_center_tag: demo.sim.pressure\npie_center_format: '{value}'\npie_group_below_pct: 8.0\npie_group_label: altro\npie_group_color: '#475569'\ndecimals: 0"),
    ("pipe", "id: o_pipe\ntype: pipe\nx: 650.0\ny: 202.0\nwidth: 290.0\nheight: 120.0\npoints:\n- - 650\n  - 242\n- - 790\n  - 242\n- - 790\n  - 312\n- - 930\n  - 312\nstroke: '#475569'\nstroke_width: 18.0\nfill_color: '#0ea5e9'\nfill_level_tag: demo.sim.level\nfill_level_scale: 0-100"),
    ("progress_bar", "id: cl1_bat_bar\ntype: progress_bar\nx: 92\ny: 304\nwidth: 166\nheight: 16\ntag: solar.battery_soc\nmin: 0\nmax: 100\nfill: '#22c55e'\nwarn_low: 20\nalarm_low: 10"),
    ("radio", "id: o_radio\ntype: radio\nx: 650.0\ny: 254.0\nwidth: 250.0\nheight: 96.0\ntag: demo.cmd.select\noptions:\n- Locale\n- Remoto\n- Fuori servizio"),
    ("recipe_panel", "id: o_recipe\ntype: recipe_panel\nx: 650.0\ny: 474.0\nwidth: 600.0\nheight: 250.0"),
    ("rect", "id: o_fx_blinktag\ntype: rect\nx: 845.0\ny: 384.0\nwidth: 180.0\nheight: 90.0\nfill: '#ef4444'\nstroke: '#fca5a5'\nstroke_width: 2.0\ncorner_radius: 6.0\nblink_mode: tag\nblink_tag: demo.sim.fault\nblink_rate_ms: 500.0"),
    ("setpoint", "id: o_setpoint\ntype: setpoint\nx: 960.0\ny: 254.0\nwidth: 290.0\nheight: 48.0\nlabel: Consegna\ntag: demo.cmd.setpoint\nmin: 0.0\nmax: 200.0\nstep: 5.0"),
    ("slider", "id: o_slider\ntype: slider\nx: 30.0\ny: 398.0\nwidth: 600.0\nheight: 44.0\ntag: demo.cmd.slider\nmin: 0.0\nmax: 100.0\nstep: 1.0\nshow_value: true\nunit: '%'"),
    ("sparkline", "id: o_spark\ntype: sparkline\nx: 650.0\ny: 96.0\nwidth: 290.0\nheight: 90.0\ntag: demo.sim.wave\nspark_color: '#22c55e'\nspark_window_s: 120.0"),
    ("state_lamp", "id: o_lamp\ntype: state_lamp\nx: 340.0\ny: 96.0\nwidth: 90.0\nheight: 56.0\ntag: demo.sim.mode\ntext_list_entries:\n- value: Auto\n  label: Auto\n  color: '#22c55e'\n- value: Manuale\n  label: Manuale\n  color: '#f59e0b'\n- value: Fermo\n  label: Fermo\n  color: '#64748b'"),
    ("symbol", "id: o_symbol\ntype: symbol\nx: 650.0\ny: 398.0\nwidth: 90.0\nheight: 90.0\nsymbol_id: pump\nstate_tag: demo.sim.running\nstate_on_color: '#22c55e'\nstate_off_color: '#64748b'\nstate_alarm_color: '#ef4444'\nsymbol_spin: tag\nsymbol_spin_tag: demo.sim.running\nsymbol_spin_s: 1.5"),
    ("table", "id: cl3_rg_table\ntype: table\nx: 28\ny: 278\nwidth: 224\nheight: 140\nlabel: '{{misure}}'\ntable_rows:\n- label: Tensione\n  tag: rack_garage.voltage\n  format: '{value:.1f} V'\n- label: Corrente\n  tag: rack_garage.current\n  format: '{value:.3f} A'\n- label: Power Factor\n  tag: rack_garage.pf\n  format: '{value:.2f}'\n- label: Energia tot.\n  tag: rack_garage.energy\n  format: '{value:.1f} kWh'\n- label: Import\n  tag: rack_garage.import\n  format: '{value:.2f} kWh'"),
    ("text", "id: cl1_title\ntype: text\nx: 400\ny: 22\ntext: '{{casa_panoramica}}'\nfont_size: 20\nfont_weight: bold\ntext_anchor: middle\ncolor: '#e2e8f0'\ngroup_id: g_header\nlocked: true"),
    ("text_list", "id: o_textlist\ntype: text_list\nx: 650.0\ny: 100.0\nwidth: 290.0\nheight: 40.0\ntag: demo.sim.mode\ntext_list_default: sconosciuto\ntext_list_default_color: '#64748b'\ntext_list_entries:\n- value: Auto\n  label: In automatico\n  color: '#22c55e'\n- value: Manuale\n  label: In manuale\n  color: '#f59e0b'\n- value: Fermo\n  label: Fermo\n  color: '#94a3b8'"),
    ("trend", "id: pro2_trend_pv1\ntype: trend\nx: 14\ny: 356\nwidth: 772\nheight: 130\ntag: pv1.corrente_a\nextra_tags:\n- pv2.corrente_a\nwindow_s: 3600\nline_color: '#22c55e'"),
    ("xy_plot", "id: o_xy\ntype: xy_plot\nx: 960.0\ny: 96.0\nwidth: 290.0\nheight: 250.0\ntag: demo.sim.pressure\ny_tag: demo.sim.flow\nxy_x_min: 0.0\nxy_x_max: 120.0\nxy_y_min: 0.0\nxy_y_max: 100.0\nxy_trail_s: 60.0"),
];

/// Un esempio YAML reale per `kind` di sorgente.
pub const SOURCE_EXAMPLES: &[(&str, &str)] = &[
    ("en_ip", "kind: en_ip\nid: enip-plc\nip: 192.168.1.10\nslot: 0\npoll_interval_ms: 500\ntags:\n- tag: pump.speed\n  plc_tag: Pump_Speed\n  data_type: real\n  writable: true\n- tag: valve.open\n  plc_tag: Valve_Open\n  data_type: bool\n  writable: true\n- tag: sensor.temp\n  plc_tag: Temperature\n  data_type: real\n  writable: false"),
    ("homeassistant", "kind: homeassistant\nid: ha-demo\nurl: http://homeassistant.local:8123\ntoken_env: HA_TOKEN\nentities:\n- tag: sala.temperatura\n  entity_id: sensor.sensoreambientesoggiorno_temperature\n- tag: luce.esterno\n  entity_id: switch.lampada_cancelletto_mauro\n  write_domain: switch\n  write_service: turn_on\n- tag: sole.elevazione\n  entity_id: sun.sun\n  attribute: elevation"),
    ("mqtt", "kind: mqtt\nid: shelly-tapparelle\nhost: 192.168.1.6\nport: 1883\nclient_id: sws-casa-shelly\nclean_session: true\nkeep_alive_secs: 30\ntopics:\n- tag: shutter.garage\n  topic: shellies/SHELLY_GARAGE_ID/roller/0/pos\n  publish_topic: shellies/SHELLY_GARAGE_ID/roller/0/command\n- tag: shutter.bagno\n  topic: shellies/SHELLY_BAGNO_ID/roller/0/pos\n  publish_topic: shellies/SHELLY_BAGNO_ID/roller/0/command\n- tag: shutter.sogg_dx\n  topic: shellies/SHELLY_SOGG_DX_ID/roller/0/pos\n  publish_topic: shellies/SHELLY_SOGG_DX_ID/roller/0/command"),
    ("opcua_client", "kind: opcua_client\nid: sim-opcua\nendpoint_url: opc.tcp://localhost:4840\nsecurity_policy: None\nauth:\n  kind: anonymous\nsubscription_interval_ms: 500\nnodes:\n- tag: sim.temperature\n  node_id: ns=1;s=Temperature\n  description: Simulated temperature\n- tag: sim.pressure\n  node_id: ns=1;s=Pressure\n  description: Simulated pressure\n- tag: sim.cycle_time\n  node_id: ns=2;s=CycleTime\n  description: Euromap 77 — CycleTime"),
    ("s7", "kind: s7\nid: plc1\nip: 192.168.1.5\nrack: 0\nslot: 1\npoll_interval_ms: 500\ntags:\n- tag: pump1.speed\n  area: db\n  db_num: 1\n  byte_offset: 0\n  data_type: real\n  writable: true\n- tag: valve1.open\n  area: db\n  db_num: 1\n  byte_offset: 4\n  data_type: bool\n  bit_offset: 0\n  writable: true\n- tag: process.temperature\n  area: db\n  db_num: 1\n  byte_offset: 6\n  data_type: real"),
];

